# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    required: true
  report_file:
    description: 'Trivy Report file'
    required: true
    default: 'trivy.json'
  working_directory:
    required: false
    description: |
      Directory to run the action on, from the repo root.
      Default is . (root of the repository)
    default: "."
  soft_fail_commenter:
    required: false
    description: If set to `true` will silently comment without breaking the build

runs:
  using: 'docker'
  image: 'Dockerfile'
  # args:
  #   - ${{ inputs.who-to-greet }}
