# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    required: true
  report_file:
    description: 'Trivy Report file'
    required: true
    default: 'trivy.json'

runs:
  using: 'docker'
  image: 'Dockerfile'
  # args:
  #   - ${{ inputs.who-to-greet }}
