name: trivy-terraform-pr-commenter release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    name: releasing trivy-terraform-pr-commenter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v3
        with:
          stable: 'false'
          go-version: '1.22'
      - run: go version

      - name: Release
        uses: goreleaser/goreleaser-action@7ec5c2b0c6cdda6e8bbb49444bc797dd33d74dd8  # v5.0.0
        with:
          version: latest
          args: release --clean --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}